name: flutter_app
description: A new Flutter application.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  intl: 0.17.0
  dio: ^3.0.10
  http: ^0.12.2
  json_string: ^2.0.1
  video_player: ^2.1.1
  animated_splash_screen: ^1.0.1+2
  dropdown_date_picker: ^0.1.1+2

flutter:

  uses-material-design: true

  assets:
    - assets/logo_nasa.png
  #   - images/a_dot_ham.jpeg

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
